<section id="lich-su-muon" class="trang-an"
    <?php echo ($active_tab != 'lich-su-muon') ? 'style="display:none;"' : ''; ?>>
    <div class="header-section">
        <h2>Lịch sử mượn thiết bị</h2>
        <div class="calendar-controls">
            <button id="btn-prev-month" class="btn btn-arrow">
                ←
            </button>
            <h3 id="current-month-year">Tháng 12, 2024</h3>
            <button id="btn-next-month" class="btn btn-arrow">
                →
            </button>
            <button id="btn-today" class="btn btn-primary">Hôm nay</button>
        </div>
    </div>

    <!-- Bộ lọc -->
    <div class="filter-section">
        <div class="filter-group">
            <label for="filter-status-history">Trạng thái:</label>
            <select id="filter-status-history">
                <option value="">Tất cả</option>
                <option value="cho-duyet">Chờ duyệt</option>
                <option value="da-duyet">Đã duyệt</option>
                <option value="da-huy">Đã hủy</option>
                <option value="tu-choi">Từ chối</option>
                <option value="dang-muon">Đang mượn</option>
                <option value="da-tra">Đã trả</option>
            </select>
        </div>
        <div class="filter-group">
            <label for="filter-equipment-history">Thiết bị:</label>
            <input type="text" id="filter-equipment-history" placeholder="Tìm theo tên thiết bị...">
        </div>
        <button id="btn-clear-filters-history" class="btn btn-outline">Xóa bộ lọc</button>
    </div>

    <!-- Khung lịch -->
    <div class="calendar-container">
        <div class="calendar-header">
            <div class="weekday">CN</div>
            <div class="weekday">T2</div>
            <div class="weekday">T3</div>
            <div class="weekday">T4</div>
            <div class="weekday">T5</div>
            <div class="weekday">T6</div>
            <div class="weekday">T7</div>
        </div>
        <div id="calendar-grid" class="calendar-grid">
            <!-- Calendar days will be generated by JavaScript -->
        </div>
    </div>

    <!-- Chi tiết ngày được chọn -->
    <div class="selected-date-details">
        <h3 id="selected-date-title">Chọn một ngày để xem chi tiết</h3>
        <div id="selected-date-loans" class="loans-list">
            <!-- Loan details for selected date will be shown here -->
        </div>
    </div>



    <!-- Loading indicator -->
    <div id="loading-history" class="loading-indicator" style="display: none;">
        <div class="spinner"></div>
        <p>Đang tải dữ liệu...</p>
    </div>
</section>